export const links = [
  {
    rank: 1,
    employee: "Rohit Sharma",
    metric: "Taylor Jordan",
    score: "100%",
  },
  {
    rank: 2,
    employee: "Alexander Johnson",
    metric: "Taylor Jordan",
    score: "99%",
  },
  {
    rank: 3,
    employee: "Bea Trice",
    metric: "Taylor Jordan",
    score: "98%",
  },
  {
    rank: 4,
    employee: "Chales Jason",
    metric: "Taylor Jordan",
    score: "97%",
  },
  {
    rank: 5,
    employee: "Ethan Brown",
    metric: "Taylor Jordan",
    score: "96%",
  },
  {
    rank: 6,
    employee: "Fiona Brown",
    metric: "Taylor Jordan",
    score: "95%",
  },
  {
    rank: 7,
    employee: "Fiona Red",
    metric: "Taylor Jordan",
    score: "94%",
  },
  {
    rank: 8,
    employee: "Fiona Yellow",
    metric: "Taylor Jordan",
    score: "93%",
  },
  {
    rank: 9,
    employee: "Isaac Harris",
    metric: "Taylor Jordan",
    score: "92%",
  },
  {
    rank: 10,
    employee: "Juliette Clark",
    metric: "Taylor Jordan",
    score: "91%",
  },
  {
    rank: 11,
    employee: "Liam Walker",
    metric: "Taylor Jordan",
    score: "90%",
  },
  {
    rank: 12,
    employee: "Liam Runner",
    metric: "Taylor Jordan",
    score: "89%",
  },
  {
    rank: 13,
    employee: "Ruby Adams",
    metric: "Taylor Jordan",
    score: "88%",
  },
  {
    rank: 14,
    employee: "Sam Philips",
    metric: "Taylor Jordan",
    score: "87%",
  },
  {
    rank: 15,
    employee: "Erl Jocson",
    metric: "Taylor Jordan",
    score: "86%",
  },
  {
    rank: 16,
    employee: "Olivia Wright",
    metric: "Taylor Jordan",
    score: "85%",
  },
  {
    rank: 17,
    employee: "King Sama",
    metric: "Taylor Jordan",
    score: "84%",
  },
  {
    rank: 18,
    employee: "Cath Consignado",
    metric: "Taylor Jordan",
    score: "83%",
  },
];

export const links2 = [
  {
    rank: 1,
    employee: "Bea Trice",
    metric: "Taylor Jordan",
    score: "100%",
  },
  {
    rank: 2,
    employee: "Alexander Johnson",
    metric: "Taylor Jordan",
    score: "99%",
  },
  {
    rank: 3,
    employee: "Rohit Sharma",
    metric: "Taylor Jordan",
    score: "98%",
  },
  {
    rank: 4,
    employee: "Chales Jason",
    metric: "Taylor Jordan",
    score: "97%",
  },
  {
    rank: 5,
    employee: "Ethan Brown",
    metric: "Taylor Jordan",
    score: "96%",
  },
  {
    rank: 6,
    employee: "Fiona Brown",
    metric: "Taylor Jordan",
    score: "95%",
  },
  {
    rank: 7,
    employee: "Fiona Red",
    metric: "Taylor Jordan",
    score: "94%",
  },
  {
    rank: 8,
    employee: "Fiona Yellow",
    metric: "Taylor Jordan",
    score: "93%",
  },
  {
    rank: 9,
    employee: "Isaac Harris",
    metric: "Taylor Jordan",
    score: "92%",
  },
  {
    rank: 10,
    employee: "Juliette Clark",
    metric: "Taylor Jordan",
    score: "91%",
  },
  {
    rank: 11,
    employee: "Liam Walker",
    metric: "Taylor Jordan",
    score: "90%",
  },
  {
    rank: 12,
    employee: "Liam Runner",
    metric: "Taylor Jordan",
    score: "89%",
  },
  {
    rank: 13,
    employee: "Ruby Adams",
    metric: "Taylor Jordan",
    score: "88%",
  },
  {
    rank: 14,
    employee: "Sam Philips",
    metric: "Taylor Jordan",
    score: "87%",
  },
  {
    rank: 15,
    employee: "Erl Jocson",
    metric: "Taylor Jordan",
    score: "86%",
  },
  {
    rank: 16,
    employee: "Olivia Wright",
    metric: "Taylor Jordan",
    score: "85%",
  },
  {
    rank: 17,
    employee: "King Sama",
    metric: "Taylor Jordan",
    score: "84%",
  },
  {
    rank: 18,
    employee: "Cath Consignado",
    metric: "Taylor Jordan",
    score: "83%",
  },
];

export const links3 = [
  {
    rank: 1,
    employee: "Bea Trice",
    metric: "Taylor Jordan",
    score: "100%",
  },
  {
    rank: 2,
    employee: "Alexander Johnson",
    metric: "Taylor Jordan",
    score: "99%",
  },
  {
    rank: 3,
    employee: "Ethan Black",
    metric: "Taylor Jordan",
    score: "98%",
  },
  {
    rank: 4,
    employee: "Chales Jason",
    metric: "Taylor Jordan",
    score: "97%",
  },
  {
    rank: 5,
    employee: "Rohit Sharma",
    metric: "Taylor Jordan",
    score: "96%",
  },
  {
    rank: 6,
    employee: "Fiona Brown",
    metric: "Taylor Jordan",
    score: "95%",
  },
  {
    rank: 7,
    employee: "Fiona Red",
    metric: "Taylor Jordan",
    score: "94%",
  },
  {
    rank: 8,
    employee: "Fiona Yellow",
    metric: "Taylor Jordan",
    score: "93%",
  },
  {
    rank: 9,
    employee: "Isaac Harris",
    metric: "Taylor Jordan",
    score: "92%",
  },
  {
    rank: 10,
    employee: "Juliette Clark",
    metric: "Taylor Jordan",
    score: "91%",
  },
  {
    rank: 11,
    employee: "Liam Walker",
    metric: "Taylor Jordan",
    score: "90%",
  },
  {
    rank: 12,
    employee: "Liam Runner",
    metric: "Taylor Jordan",
    score: "89%",
  },
  {
    rank: 13,
    employee: "Ruby Adams",
    metric: "Taylor Jordan",
    score: "88%",
  },
  {
    rank: 14,
    employee: "Sam Philips",
    metric: "Taylor Jordan",
    score: "87%",
  },
  {
    rank: 15,
    employee: "Erl Jocson",
    metric: "Taylor Jordan",
    score: "86%",
  },
  {
    rank: 16,
    employee: "Olivia Wright",
    metric: "Taylor Jordan",
    score: "85%",
  },
  {
    rank: 17,
    employee: "King Sama",
    metric: "Taylor Jordan",
    score: "84%",
  },
  {
    rank: 18,
    employee: "Cath Consignado",
    metric: "Taylor Jordan",
    score: "83%",
  },
];
