export const links = [
  {
    rank: 1,
    employee: "Rohit Sharma",
    metric: "Pushkar Misra",
    score: "100%",
  },
  {
    rank: 2,
    employee: "Rohit Sharma",
    metric: "Pushkar Misra",
    score: "100%",
  },
  {
    rank: 3,
    employee: "Rohit Sharma",
    metric: "Pushkar Misra",
    score: "100%",
  },
  {
    rank: 4,
    employee: "Rohit Sharma",
    metric: "Pushkar Misra",
    score: "100%",
  },
  {
    rank: 5,
    employee: "Rohit Sharma",
    metric: "Pushkar Misra",
    score: "100%",
  },
  {
    rank: 6,
    employee: "Rohit Sharma",
    metric: "Pushkar Misra",
    score: "100%",
  },
  {
    rank: 7,
    employee: "Rohit Sharma",
    metric: "Pushkar Misra",
    score: "100%",
  },
  {
    rank: 8,
    employee: "Rohit Sharma",
    metric: "Pushkar Misra",
    score: "100%",
  },
  {
    rank: 9,
    employee: "Rohit Sharma",
    metric: "Pushkar Misra",
    score: "100%",
  },
  {
    rank: 10,
    employee: "Rohit Sharma",
    metric: "Pushkar Misra",
    score: "100%",
  },
  {
    rank: 11,
    employee: "Rohit Sharma",
    metric: "Pushkar Misra",
    score: "100%",
  },
  {
    rank: 12,
    employee: "Rohit Sharma",
    metric: "Pushkar Misra",
    score: "100%",
  },
  {
    rank: 13,
    employee: "Rohit Sharma",
    metric: "Pushkar Misra",
    score: "100%",
  },
  {
    rank: 14,
    employee: "Rohit Sharma",
    metric: "Pushkar Misra",
    score: "100%",
  },
  {
    rank: 15,
    employee: "Rohit Sharma",
    metric: "Pushkar Misra",
    score: "100%",
  },
  {
    rank: 16,
    employee: "Rohit Sharma",
    metric: "Pushkar Misra",
    score: "100%",
  },
  {
    rank: 17,
    employee: "Rohit Sharma",
    metric: "Pushkar Misra",
    score: "100%",
  },
  {
    rank: 18,
    employee: "Rohit Sharma",
    metric: "Pushkar Misra",
    score: "100%",
  },
];
